### ISSUE TITLE
Item Click does not working

### ISSUE THREAD

**Issue by beraybentesen** [MiguelCatalan/MaterialSearchView#128]
Item click does nothing. For example : 

 materialSearchView.setOnItemClickListener((adapterView, view, i, l) -> {
            DataModel dataModel = recList.get(i);
            System.out.println("NAME " + dataModel.getName());
        });

**Comment by Chefty** [comment]
@beraybentesen 
Did you find a solution ? No way to catch item click trigger for me...

Thanks

**Comment by bellierjonathan** [comment]
It works for me.
```
mSearchBox.setOnItemClickListener(new AdapterView.OnItemClickListener() {
     @Override
     public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
          Log.d("test", "test");
     }
});
```

And it works with custom interface too :/

**Comment by 0v4tsug** [comment]
already tried that way, also with 
searchView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Log.d("test","comeOnPleaseDoIt");
            }
, but doesnt work :(

**Comment by CongBaDo** [comment]
Set Adapter for SearchView, OnItemClick will work
mSearchView.setAdapter(new SearchAdapter(this, results));

**Comment by TIS-OMiddle** [comment]
OK...maybe I know why....
you may call the "setSuggestions()" method after you set the "OnItemClickListener", and this is the reason.
In "setSuggestions()" method, it will do:
`
setOnItemClickListener(new AdapterView.OnItemClickListener() {
                @Override
                public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                    setQuery((String) adapter.getItem(position), submit);
                }
            });
`
this listener is uesd to change the "query text" and will cover your listener. so if you have set a listener and want to update your suggestions, you should call "setAdapter(new SearchAdapter(this, results));" instead of "setSuggestions()"

**Comment by beraybentesen** [comment]
I fixed this issue by implementing additional interface and calling it but can't remember what exactly I did.
