### ISSUE TITLE
InflateException Error

### ISSUE THREAD

**Issue by kuraydev** [MiguelCatalan/MaterialSearchView#91]
Hello,
I was using your library and i love it ! 
Unfortunately, after google released new update, i cannot inflate your class.

Caused by: android.view.InflateException: Binary XML file line #27: Error inflating class com.miguelcatalan.materialsearchview.MaterialSearchView

Can you help me about it?

**Comment by alvarlagerlof** [comment]
I have the same problem

**Comment by HanderWei** [comment]
@WrathChaos @alvarlagerlof Did you fix this problem?

**Comment by alvarlagerlof** [comment]
Nope

**Comment by chap19150** [comment]
I have the same issue

**Comment by PondThaitay** [comment]
Me too

**Comment by codenpk** [comment]
Same issue...

**Comment by irwing844** [comment]
NoBody?

**Comment by codenpk** [comment]
removed this and using PlacePicker

**Comment by kennyk** [comment]
This is happening because you already have an .xml file with the same name in the module that you are including MaterialSearchView into. 

In my case, I already had a `layout/search_view.xml` file in my app module - renaming it fixed the problem for me. I guess it could also be one of the drawables, or any other resource, but I'd try the layouts first.

**Comment by jelther** [comment]
I had this problem too. Unfortunately, having a .xml file with the same name (search_view) causes the crash. Removing it worked!

**Comment by Praveenvermatech** [comment]
same issue on my end...
 android.view.InflateException: Binary XML file line #11: Binary XML file line #63: Error inflating class br.com.mauker.materialsearchview.MaterialSearchView
